### ISSUE TITLE
switching hls stream

### ISSUE THREAD

**Issue by dob123** [bitmovin/bitdash-demo-playlist#1]
I dont know if is intended but when trying to switch between a hls stream receive the following errors:

TypeError: player.getCurrentTime is not a function
TypeError player.removeEventHandler is not a function

The player.removeEventHandler error is generated when trying to click on another link in the playlist, ie change the stream

Using firefox or safari same error occurs

**Comment by ReinhardG** [comment]
That's definitely not how it should work - we will check on that.

Is the issue blocking your current development?

**Comment by dob123** [comment]
Hi Reinhard,

Thanks for the reply, i wouldn't say you are blocking my development as without your playlist I wouldn't be anywhere near as far along in this project as I am so thanks for even releasing it.

To finish development I just need this ability to switch between live hls, currently I believe the api call for the change in video on video end but obviously my m3u8 has no end. Anything you can do to help would be appreciated. I know it's Christmas so thanks very much for anything you can do

**Comment by ReinhardG** [comment]
Ok, for changing the (live) source (DASH as well as HLS), you can simply use the .load() API call, like described at http://developer.dash-player.com/javascript-api#playback-commands. 

Please also make sure to use the latest player version from https://portal.bitcodin.com/portal/

**Comment by dob123** [comment]
Thanks, so for clarification instead of the onPlaybackFinished I will use .load() call

**Comment by dob123** [comment]
This issue may be resolved by using api version 4

**Comment by dob123** [comment]
the .load() API call has been removed as of version 4, as have a few others

**Comment by dweinber** [comment]
The load call has definitely not been removed. I think this is due to an API change in v4. The setup call now returns a Promise instead of the player object. Please have a look at the migration guide at http://developer.dash-player.com/migration-guide

The demo has not yet been updated to these changes.

**Comment by dob123** [comment]
Are there any plans to update this demo?

**Comment by dweinber** [comment]
We will update the demo soon, we'll let you know once this has been done.

**Comment by dweinber** [comment]
We just updated the demo.
@dob123, could you please let us know if your issue has been resolved?

**Comment by dob123** [comment]
Hi, thanks for the update.

There is now a ReferenceError line 215 bitdash is not defined

All i did was overwrite the main.js with your new update, should I have changed all files also?

**Comment by dweinber** [comment]
The index.html file had been changed as well, the player's Javascript file is now included there. That's why it is missing now if you updated the main.js only.

**Comment by dob123** [comment]
Thanks Daniel, sorry. Will update properly now and let you know. I'm sure will be all working. Appreciate your time

**Comment by dob123** [comment]
Updated correctly and is now working perfectly, much appreciated.

**Comment by dweinber** [comment]
Thanks for letting us know, I'm glad it's working for you now!
